name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Dependencies
      run: ./frontend/ npm install

    - name: Run Tests
      run: ./frontend/ npm test

    - name: Build
      run: ./frontend/ npm run build


